### ISSUE TITLE
how to disable secure boot?

### ISSUE THREAD

**Issue by Jamessigur** [ryanrudolfoba/SecureBootForSteamDeck#3]
how do I disable secure boot, I rebooted my Steam Deck and now it gives me a security and blocking error, how do I restore my Steam Deck?

**Comment by ryanrudolfoba** [comment]
Boot back using your Linux usb flash drive that contains the keys and follow the steps -

https://github.com/ryanrudolfoba/SecureBootForSteamDeck#instructions---revert-changes-and-disable-secure-boot

**Comment by Jamessigur** [comment]
> Boot back using your Linux usb flash drive that contains the keys and follow the steps -
> 
> https://github.com/ryanrudolfoba/SecureBootForSteamDeck#instructions---revert-changes-and-disable-secure-boot

I broken my usb-flash with keys....how restore steam deck?

**Comment by ryanrudolfoba** [comment]
> > Boot back using your Linux usb flash drive that contains the keys and follow the steps -
> > https://github.com/ryanrudolfoba/SecureBootForSteamDeck#instructions---revert-changes-and-disable-secure-boot
> 
> I broken my usb-flash with keys....how restore steam deck?

Without the keys you cant disable secure boot.

![Screenshot_20230512-085402](https://github.com/ryanrudolfoba/SecureBootForSteamDeck/assets/98122529/acc4965d-06f2-4d24-996e-07ed4d3e8f29)

**Comment by ryanrudolfoba** [comment]
Without the keys you cant disable secure boot.


![](https://user-images.githubusercontent.com/98122529/237976202-acc4965d-06f2-4d24-996e-07ed4d3e8f29.png)

**Comment by WinkelCode** [comment]
@ryanrudolfoba I think it would be useful to test if this works to reset the Secure Boot keys: Hold Volume Down, the "..." button, and power on. Should be some type of CMOS reset apparently.

I just randomly came across the repo, I don't use Secure Boot on my Deck and don't want to risk any issues just to test this myself. I have used the key combination to reset BIOS/Firmware settings though.

**Comment by MoltenHydrogen** [comment]
Was able to reset my bios with an update. I ran into an error while verifying (it couldn't find the efi folder bc i was in a live disk) and had to reboot. I could get into my existing windows install but anything else would give me a security violation. I got a bios flasher for windows [here](https://www.reddit.com/r/SteamDeckTinker/comments/uejm4i/uefi_updates_for_windows_users/) and the updates [here](https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/). I am about to check if it will actually let me into other OSes, but considering my audio came back (my faulty secure boot apparently broke the audio) I'm assuming that the update worked.

Edit: works. not going to try secure boot again as I realized it didn't work to get vanguard working anyway

**Comment by Ultra-Smork** [comment]
@MoltenHydrogen I know that is an old comment, but do you remember what was the update  that you used?

**Comment by chessset5** [comment]
@Ultra-Smork I followed the instructions on the reddit post linked and just used the `.fd` files found in the file server and I was able to get a bios back.
Of course I was able to only do this because I was able to at least get into Windows.
Reddit post: 
https://www.reddit.com/r/SteamDeckTinker/comments/uejm4i/uefi_updates_for_windows_users/
File server files:
https://content.pvabel.net/devices/SteamDeck/UEFI/
https://content.pvabel.net/devices/SteamDeck/UEFI/Flasher/

My steamOS got corrupted in the process, but following the below post from LazerWalker, specifically the 9 steps in the *Fixing The GRUB Partition Table* section, I was able to get SteamOS back.
LazerWalker post:
https://blog.lazerwalker.com/2024/10/23/dual-booting-steam-deck.html

_note that there is an error on step 4 in LazerWalker's post, `sudo fdisk -l /dev/nve0n1` should be `sudo fdisk -l /dev/nvme0n1`_

You might need to go into windows and specifically have it boot last in the boot menu. 
You can do this with the dual boot fix script which is hosted here on mediafire:
https://www.mediafire.com/file/w7jswsuctvnnd7k/Dual+Boot+Fix.zip/file

It is a part of the steamdeck dual boot tool [SteamDeck_rEFInd](https://github.com/jlobue10/SteamDeck_rEFInd)
https://github.com/jlobue10/SteamDeck_rEFInd?tab=readme-ov-file

_note that the main underlying command for this tool is the `bcedit` command in powershell, so if you have some cli skills, you could probably use the command to push windows to the bottom of the boot order in windows your self._

If that fails you, at bare minimum, since you can get back into the bios, you can use a tool like https://partedmagic.com/ to nuke the partition table and re-install windows and/or steamOS; so long as you are fine with loosing the existing data you had on your steamdeck and re-downloading everything again. But this is a last resort thing. You will get SteamOS back, but **everything will be gone and back to factory settings**.
